import "./globals.css";

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import React from "react";

import Footer from "@/components/organisms/footer";
import Header from "@/components/organisms/header";
import { CartProvider } from "@/contexts/cart/CartContext";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable}>
      <body className="font-nunito antialiased">
        <CartProvider>
          <Header />
          <div className="mt-19">{children}</div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
